// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClvWJSC3R-aJrunWaXXnyZE9TE-0fZM_o',
    appId: '1:963113672836:web:f745152a1fab2fa957a2d1',
    messagingSenderId: '963113672836',
    projectId: 'calib-640db',
    authDomain: 'calib-640db.firebaseapp.com',
    storageBucket: 'calib-640db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBownLFdUJr6IiCuwiLFzMi_bGLePoUerU',
    appId: '1:963113672836:android:5373b9496cfebf9f57a2d1',
    messagingSenderId: '963113672836',
    projectId: 'calib-640db',
    storageBucket: 'calib-640db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSK9FGZSyYEgn6hlo6TxzekYOdowBnkE',
    appId: '1:963113672836:ios:0612b41359d7d71457a2d1',
    messagingSenderId: '963113672836',
    projectId: 'calib-640db',
    storageBucket: 'calib-640db.firebasestorage.app',
    iosBundleId: 'com.example.calibApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdSK9FGZSyYEgn6hlo6TxzekYOdowBnkE',
    appId: '1:963113672836:ios:0612b41359d7d71457a2d1',
    messagingSenderId: '963113672836',
    projectId: 'calib-640db',
    storageBucket: 'calib-640db.firebasestorage.app',
    iosBundleId: 'com.example.calibApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClvWJSC3R-aJrunWaXXnyZE9TE-0fZM_o',
    appId: '1:963113672836:web:ff6b4f17637127a057a2d1',
    messagingSenderId: '963113672836',
    projectId: 'calib-640db',
    authDomain: 'calib-640db.firebaseapp.com',
    storageBucket: 'calib-640db.firebasestorage.app',
  );
}
